In [1]:
import cv2 

In [2]:
face_Cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [3]:
img=cv2.imread("C:\\Users\\hp\\Downloads\\WhatsApp Image 2024-05-26 at 2.33.02 PM.jpeg",cv2.COLOR_BGR2GRAY)
img

array([[[214, 214, 214],
        [214, 214, 214],
        [214, 214, 214],
        ...,
        [214, 214, 214],
        [214, 214, 214],
        [214, 214, 214]],

       [[214, 214, 214],
        [214, 214, 214],
        [214, 214, 214],
        ...,
        [214, 214, 214],
        [214, 214, 214],
        [214, 214, 214]],

       [[214, 214, 214],
        [214, 214, 214],
        [214, 214, 214],
        ...,
        [214, 214, 214],
        [214, 214, 214],
        [214, 214, 214]],

       ...,

       [[161, 170, 183],
        [159, 168, 181],
        [156, 165, 178],
        ...,
        [109, 118, 131],
        [109, 118, 131],
        [109, 118, 131]],

       [[147, 156, 169],
        [146, 155, 168],
        [143, 152, 165],
        ...,
        [109, 118, 131],
        [109, 118, 131],
        [109, 118, 131]],

       [[135, 144, 157],
        [133, 142, 155],
        [130, 139, 152],
        ...,
        [109, 118, 131],
        [109, 118, 131],
        [109, 118, 131]]

In [4]:
cv2.imshow("image",img)  # open a new window to show the image
cv2.waitKey(0)          # if you want to close the image press 0
cv2.destroyAllWindows() # the window will be closed

In [5]:
# all together
# we are reading an image
# we are showing the imgage
# we are applying a wait key
# we are closing the image
img=cv2.imread("C:\\Users\\hp\\Downloads\\WhatsApp Image 2024-05-26 at 2.33.02 PM.jpeg",
               cv2.COLOR_BGR2GRAY)

cv2.imshow("image",img)  # open a new window to show the image
cv2.waitKey(0)          # if you want to close the image press 0
cv2.destroyAllWindows()

In [6]:
img=cv2.imread("C:\\Users\\hp\\Downloads\\WhatsApp Image 2024-05-26 at 2.33.02 PM.jpeg",
               cv2.COLOR_BGR2GRAY)

start_window=(5,5)
end_window= (200,200)
color=(0,0,255)
thikness=5
rec_image=cv2.rectangle(img,
              start_window,
              end_window,
              color,
              thikness)

cv2.imshow("image",rec_image)

cv2.waitKey(0)         
cv2.destroyAllWindows()

# This is the problem 
# we need to provide correct values of start window and end window

In [7]:
img=cv2.imread("C:\\Users\\hp\\Downloads\\WhatsApp Image 2024-05-26 at 2.33.02 PM.jpeg",
               cv2.COLOR_BGR2GRAY)
face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
faces=face_cascade.detectMultiScale(img,1.1,4)
print(faces)
for (x,y,w,h) in faces:
    print(x,y)
    print(w,h)
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),3)   # B G  R  Red Is ON

[[ 569 1928   30   30]
 [ 448  729  913  913]
 [1265 2548  159  159]
 [ 230 2167  123  123]
 [ 913 2195   64   64]
 [ 170 2148   64   64]]
569 1928
30 30
448 729
913 913
1265 2548
159 159
230 2167
123 123
913 2195
64 64
170 2148
64 64


In [8]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [25]:
cap=cv2.VideoCapture(0)
while cap.isOpened():
    has_frame,frame=cap.read()
    imag=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    faces=face_cascade.detectMultiScale(imag,1.1,4)
    for (x,y,w,h) in faces:
        cv2.rectangle(imag,(x,y),(x+h,y+w),(255,0,0),3)
    cv2.imshow('image',imag)
    if cv2.waitKey(1) & 0xFF== ord('q'):
        break
cap.release()
cv2.destroyAllWindows() 



In [10]:
import cv2
eye_cascade=cv2.CascadeClassifier('haarcascade_eye.xml')
face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [11]:
cap=cv2.VideoCapture(0)
while True:
    has_frame,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray=gray[y:y+h,x:x+w] #region of the image
        roi_color=frame[y:y+h,x:x+w]
        eyes=eye_cascade.detectMultiScale(roi_gray)
        for (e_x,e_y,e_w,e_h) in eyes:
            cv2.rectangle(roi_color,(e_x,e_y),(e_x+e_w,e_y+e_h),(0,255,0),2)
    cv2.imshow('imag',frame)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [12]:
image1 = cv2.imread('skoda-india-front-license-plate.jpg')
image1


array([[[ 33,  81,  57],
        [ 33, 117,  92],
        [ 28, 141, 113],
        ...,
        [110, 120, 114],
        [ 72,  84,  88],
        [ 38,  68,  69]],

       [[ 42,  85,  58],
        [ 31,  98,  77],
        [ 32,  97,  81],
        ...,
        [ 46,  69,  65],
        [ 78,  98,  93],
        [ 98, 120, 118]],

       [[ 37,  78,  57],
        [ 38,  80,  62],
        [ 62,  82,  63],
        ...,
        [ 49,  81,  80],
        [116, 134, 127],
        [155, 165, 159]],

       ...,

       [[119, 108, 100],
        [118, 110,  97],
        [120, 112,  95],
        ...,
        [ 61,  51,  41],
        [ 63,  52,  44],
        [ 65,  56,  47]],

       [[113,  98,  89],
        [112, 103,  89],
        [116, 107,  93],
        ...,
        [ 63,  53,  43],
        [ 63,  54,  40],
        [ 62,  54,  41]],

       [[113,  95,  84],
        [117, 104,  90],
        [116, 105,  97],
        ...,
        [ 62,  53,  40],
        [ 64,  55,  42],
        [ 60,  54,  43]]

In [13]:
number_plate = cv2.CascadeClassifier('haarcascade_license_plate_rus_16stages.xml')

cap = cv2.VideoCapture(0)
while True:
    has_frame,frame = cap.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    vehicile = number_plate.detectMultiScale(gray,1.1,5)
    for (x,y,w,h) in vehicile:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h,x:x+w]
        roi_color = frame[y:y+h,x:x+w]
    cv2.imshow('imag',image1)
    if cv2.waitKey(1) & 0xFF ==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


In [14]:
cap=cv2.VideoCapture(0)
while cap.isOpened():
    has_frame,frame=cap.read()
    imag=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    faces=face_cascade.detectMultiScale(imag,1.1,4)
    for (x,y,w,h) in faces:
        cv2.rectangle(imag,(x,y),(x+h,y+w),(255,0,0),3)
    cv2.imshow('image',imag)
    if cv2.waitKey(1) & 0xFF== ord('q'):
        break
cap.release()
cv2.destroyAllWindows() 



In [2]:
import cv2
number_plate = cv2.CascadeClassifier("haarcascade_russian_plate_number.xml")
cap = cv2.VideoCapture('1900-151662242_large.mp4')
while cap.isOpened():    
    ret, frame = cap.read() 
    cv2.imshow('frame', frame)
    vehicel=number_plate.detectMultiScale(cap,1.1,4)
for (x,y,w,h) in vehicel:
    print(x,y)
    print(w,h)
    cv2.rectangle(cap,(x,y),(x+w,y+h),(0,0,255),3)
    if cv2.waitKey(1) & 0xFF == ord('q'): 
        break
cap.release() 
cv2.destroyAllWindows()


error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'detectMultiScale'
> Overload resolution failed:
>  - image is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'image'


In [53]:
# importing libraries
import cv2

# Create a VideoCapture object and read from input file
cap = cv2.VideoCapture('1900-151662242_large.mp4')

# Check if camera opened successfully
if (cap.isOpened()== False):
    print("Error opening video file")

# Read until video is completed
while(cap.isOpened()):
    
# Capture frame-by-frame
    ret, frame = cap.read()
    if ret == True:
    # Display the resulting frame
        cv2.imshow('Frame', frame)
        
    # Press Q on keyboard to exit
        if cv2.waitKey(25) & 0xFF == ord('q'):
            break

# Break the loop
    else:
        break

# When everything done, release
# the video capture object
cap.release()

# Closes all the frames
cv2.destroyAllWindows()

In [15]:
import cv2
cap = cv2.VideoCapture() 
number_plate = cv2.CascadeClassifier('haarcascade_russian_plate_number.xml')  # Replace with the correct path to the XML file
while True:
    ret, frame = cap.read()  # Read the frame
    if not ret:
        break
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)  
        vehicles = number_plate.detectMultiScale(gray, 1.1, 4)  
        for (x, y, w, h) in vehicles:
            cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 2)  
            cv2.imshow('frame', frame) 
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
cap.release()  
cv2.destroyAllWindows() 


In [16]:
import cv2
img=cv2.imread('skoda-india-front-license-plate.jpg',cv2.COLOR_BGR2GRAY)
face_cascade=cv2.CascadeClassifier('haarcascade_russian_plate_number.xml')
faces=face_cascade.detectMultiScale(img,1.2,5)
for (x,y,w,h) in faces:
    print(x,y)
    print(w,h)
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),3)
## B G  R  Red Is ON
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()



678 374
146 49


In [17]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()